### PR TITLE
Feature addition: ability to dump and delete database content

### PR DESCRIPTION
**Pull request by divyenduz**
- Ability to dump db
	- Used the getSummary interface for taking a dump, we can introduce an import functionality later.

- Ability to remove db data
	- Made collection.truncate() to return uniformly for mongodb, sqlite collection. We need to make an interface for this should we need to add support for more databases.

### CODE REVIEW

**Comment by muatik** [comment]
@divyenduz sorry for being late. thank you, I will merge this soon.

**Comment by divyenduz** [comment]
No issues, let me know if anything needs to be changed.

**Comment by divyenduz** [comment]
Hey, long time. Let me know if any thing needs to be implemented from my end on this one. Also, let me know any other issues / features I can take up. 👍

**Comment by muatik** [comment]
I will handle this within two days. for now, nothing is required from your side, thank you again.

**Comment by divyenduz** [comment]
Resolves https://github.com/muatik/flask-profiler/pull/41

**Pull request merged**
